//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.0.0.
namespace Dc.Elements
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para xml:lang="en">This is the default type for all of the DC elements.
    ///            It permits text content only with optional
    ///            xml:lang attribute.
    ///            Text is allowed because mixed="true", but sub-elements
    ///            are disallowed because minOccurs="0" and maxOccurs="0" 
    ///            are on the xs:any tag.
    ///
    ///    	    This complexType allows for restriction or extension permitting
    ///            child elements.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SimpleLiteral", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("any", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contributor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coverage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Creator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Date))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Description))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Format))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Identifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Language))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Publisher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rights))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Source))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Title))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Type))]
    public partial class SimpleLiteral
    {
    }
    
    /// <summary>
    /// <para xml:lang="en">This complexType is included as a convenience for schema authors who need to define a root
    ///    		or container element for all of the DC elements.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("elementContainer", Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schemas.Metadata))]
    public partial class ElementContainer : IElementsGroup
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SimpleLiteral> _any;
        
        [System.Xml.Serialization.XmlElementAttribute("any", Namespace="http://purl.org/dc/elements/1.1/")]
        public System.Collections.ObjectModel.Collection<SimpleLiteral> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Any-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ElementContainer" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElementContainer" /> class.</para>
        /// </summary>
        public ElementContainer()
        {
            this._any = new System.Collections.ObjectModel.Collection<SimpleLiteral>();
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">This group is included as a convenience for schema authors
    ///            who need to refer to all the elements in the 
    ///            http://purl.org/dc/elements/1.1/ namespace.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    public partial interface IElementsGroup
    {
        
        System.Collections.ObjectModel.Collection<SimpleLiteral> Any
        {
            get;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("title", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Title : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("creator", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Creator : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("subject", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Subject : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("description", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Description : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("publisher", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Publisher : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("contributor", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Contributor : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("date", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Date : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("type", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Type : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("format", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Format : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("identifier", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Identifier : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("source", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Source : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("language", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Language : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("relation", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Relation : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("coverage", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Coverage : SimpleLiteral
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rights", Namespace="http://purl.org/dc/elements/1.1/")]
    public partial class Rights : SimpleLiteral
    {
    }
}
